/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTransactionRouteImport } from './routes/_app/transaction'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppCategoriesCreateRouteImport } from './routes/_app/categories/create'
import { Route as AppCategoriesCategoryIdRouteImport } from './routes/_app/categories/$categoryId'
import { Route as AppAccountsCreateRouteImport } from './routes/_app/accounts/create'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTransactionRoute = AppTransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesCreateRoute = AppCategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesCategoryIdRoute = AppCategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsCreateRoute = AppAccountsCreateRouteImport.update({
  id: '/accounts/create',
  path: '/accounts/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transaction': typeof AppTransactionRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/categories/create': typeof AppCategoriesCreateRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transaction': typeof AppTransactionRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/categories/create': typeof AppCategoriesCreateRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transaction': typeof AppTransactionRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/accounts/create': typeof AppAccountsCreateRoute
  '/_app/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/_app/categories/create': typeof AppCategoriesCreateRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/settings'
    | '/transaction'
    | '/login'
    | '/register'
    | '/'
    | '/accounts/$accountId'
    | '/accounts/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/accounts'
    | '/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/settings'
    | '/transaction'
    | '/login'
    | '/register'
    | '/'
    | '/accounts/$accountId'
    | '/accounts/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/accounts'
    | '/categories'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/transaction'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/create'
    | '/_app/categories/$categoryId'
    | '/_app/categories/create'
    | '/_app/accounts/'
    | '/_app/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/transaction': {
      id: '/_app/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof AppTransactionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/create': {
      id: '/_app/categories/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof AppCategoriesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$categoryId': {
      id: '/_app/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AppCategoriesCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/create': {
      id: '/_app/accounts/create'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof AppAccountsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionRoute: typeof AppTransactionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsCreateRoute: typeof AppAccountsCreateRoute
  AppCategoriesCategoryIdRoute: typeof AppCategoriesCategoryIdRoute
  AppCategoriesCreateRoute: typeof AppCategoriesCreateRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionRoute: AppTransactionRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsCreateRoute: AppAccountsCreateRoute,
  AppCategoriesCategoryIdRoute: AppCategoriesCategoryIdRoute,
  AppCategoriesCreateRoute: AppCategoriesCreateRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
