/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppExchangeRatesRouteImport } from './routes/_app/exchange-rates'
import { Route as AppTransfersIndexRouteImport } from './routes/_app/transfers/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppTransfersCreateRouteImport } from './routes/_app/transfers/create'
import { Route as AppTransfersTransferIdRouteImport } from './routes/_app/transfers/$transferId'
import { Route as AppTransactionsCreateRouteImport } from './routes/_app/transactions/create'
import { Route as AppCategoriesCreateRouteImport } from './routes/_app/categories/create'
import { Route as AppCategoriesCategoryIdRouteImport } from './routes/_app/categories/$categoryId'
import { Route as AppAccountsCreateRouteImport } from './routes/_app/accounts/create'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppTransactionsShowTransactionIdRouteImport } from './routes/_app/transactions/show/$transactionId'
import { Route as AppTransactionsEditTransactionIdRouteImport } from './routes/_app/transactions/edit/$transactionId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppExchangeRatesRoute = AppExchangeRatesRouteImport.update({
  id: '/exchange-rates',
  path: '/exchange-rates',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersCreateRoute = AppTransfersCreateRouteImport.update({
  id: '/transfers/create',
  path: '/transfers/create',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersTransferIdRoute = AppTransfersTransferIdRouteImport.update({
  id: '/transfers/$transferId',
  path: '/transfers/$transferId',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsCreateRoute = AppTransactionsCreateRouteImport.update({
  id: '/transactions/create',
  path: '/transactions/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesCreateRoute = AppCategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesCategoryIdRoute = AppCategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsCreateRoute = AppAccountsCreateRouteImport.update({
  id: '/accounts/create',
  path: '/accounts/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsShowTransactionIdRoute =
  AppTransactionsShowTransactionIdRouteImport.update({
    id: '/transactions/show/$transactionId',
    path: '/transactions/show/$transactionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppTransactionsEditTransactionIdRoute =
  AppTransactionsEditTransactionIdRouteImport.update({
    id: '/transactions/edit/$transactionId',
    path: '/transactions/edit/$transactionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/exchange-rates': typeof AppExchangeRatesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/categories/create': typeof AppCategoriesCreateRoute
  '/transactions/create': typeof AppTransactionsCreateRoute
  '/transfers/$transferId': typeof AppTransfersTransferIdRoute
  '/transfers/create': typeof AppTransfersCreateRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/transactions/edit/$transactionId': typeof AppTransactionsEditTransactionIdRoute
  '/transactions/show/$transactionId': typeof AppTransactionsShowTransactionIdRoute
}
export interface FileRoutesByTo {
  '/exchange-rates': typeof AppExchangeRatesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/categories/create': typeof AppCategoriesCreateRoute
  '/transactions/create': typeof AppTransactionsCreateRoute
  '/transfers/$transferId': typeof AppTransfersTransferIdRoute
  '/transfers/create': typeof AppTransfersCreateRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/transactions/edit/$transactionId': typeof AppTransactionsEditTransactionIdRoute
  '/transactions/show/$transactionId': typeof AppTransactionsShowTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/exchange-rates': typeof AppExchangeRatesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/accounts/create': typeof AppAccountsCreateRoute
  '/_app/categories/$categoryId': typeof AppCategoriesCategoryIdRoute
  '/_app/categories/create': typeof AppCategoriesCreateRoute
  '/_app/transactions/create': typeof AppTransactionsCreateRoute
  '/_app/transfers/$transferId': typeof AppTransfersTransferIdRoute
  '/_app/transfers/create': typeof AppTransfersCreateRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/transactions/edit/$transactionId': typeof AppTransactionsEditTransactionIdRoute
  '/_app/transactions/show/$transactionId': typeof AppTransactionsShowTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/exchange-rates'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/'
    | '/accounts/$accountId'
    | '/accounts/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/transactions/create'
    | '/transfers/$transferId'
    | '/transfers/create'
    | '/accounts'
    | '/categories'
    | '/transactions'
    | '/transfers'
    | '/transactions/edit/$transactionId'
    | '/transactions/show/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/exchange-rates'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/'
    | '/accounts/$accountId'
    | '/accounts/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/transactions/create'
    | '/transfers/$transferId'
    | '/transfers/create'
    | '/accounts'
    | '/categories'
    | '/transactions'
    | '/transfers'
    | '/transactions/edit/$transactionId'
    | '/transactions/show/$transactionId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/exchange-rates'
    | '/_app/profile'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/create'
    | '/_app/categories/$categoryId'
    | '/_app/categories/create'
    | '/_app/transactions/create'
    | '/_app/transfers/$transferId'
    | '/_app/transfers/create'
    | '/_app/accounts/'
    | '/_app/categories/'
    | '/_app/transactions/'
    | '/_app/transfers/'
    | '/_app/transactions/edit/$transactionId'
    | '/_app/transactions/show/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exchange-rates': {
      id: '/_app/exchange-rates'
      path: '/exchange-rates'
      fullPath: '/exchange-rates'
      preLoaderRoute: typeof AppExchangeRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/create': {
      id: '/_app/transfers/create'
      path: '/transfers/create'
      fullPath: '/transfers/create'
      preLoaderRoute: typeof AppTransfersCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/$transferId': {
      id: '/_app/transfers/$transferId'
      path: '/transfers/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof AppTransfersTransferIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/create': {
      id: '/_app/transactions/create'
      path: '/transactions/create'
      fullPath: '/transactions/create'
      preLoaderRoute: typeof AppTransactionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/create': {
      id: '/_app/categories/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof AppCategoriesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$categoryId': {
      id: '/_app/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AppCategoriesCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/create': {
      id: '/_app/accounts/create'
      path: '/accounts/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof AppAccountsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/show/$transactionId': {
      id: '/_app/transactions/show/$transactionId'
      path: '/transactions/show/$transactionId'
      fullPath: '/transactions/show/$transactionId'
      preLoaderRoute: typeof AppTransactionsShowTransactionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/edit/$transactionId': {
      id: '/_app/transactions/edit/$transactionId'
      path: '/transactions/edit/$transactionId'
      fullPath: '/transactions/edit/$transactionId'
      preLoaderRoute: typeof AppTransactionsEditTransactionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExchangeRatesRoute: typeof AppExchangeRatesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsCreateRoute: typeof AppAccountsCreateRoute
  AppCategoriesCategoryIdRoute: typeof AppCategoriesCategoryIdRoute
  AppCategoriesCreateRoute: typeof AppCategoriesCreateRoute
  AppTransactionsCreateRoute: typeof AppTransactionsCreateRoute
  AppTransfersTransferIdRoute: typeof AppTransfersTransferIdRoute
  AppTransfersCreateRoute: typeof AppTransfersCreateRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppTransactionsEditTransactionIdRoute: typeof AppTransactionsEditTransactionIdRoute
  AppTransactionsShowTransactionIdRoute: typeof AppTransactionsShowTransactionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExchangeRatesRoute: AppExchangeRatesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsCreateRoute: AppAccountsCreateRoute,
  AppCategoriesCategoryIdRoute: AppCategoriesCategoryIdRoute,
  AppCategoriesCreateRoute: AppCategoriesCreateRoute,
  AppTransactionsCreateRoute: AppTransactionsCreateRoute,
  AppTransfersTransferIdRoute: AppTransfersTransferIdRoute,
  AppTransfersCreateRoute: AppTransfersCreateRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppTransactionsEditTransactionIdRoute: AppTransactionsEditTransactionIdRoute,
  AppTransactionsShowTransactionIdRoute: AppTransactionsShowTransactionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
